name = "eremit"
license = "MIT"
licenselink = "https://github.com/lauthals/eremit/blob/master/LICENSE"
description = "A cleaner fork of heremit, the minimal and fast hugo theme for bloggers."
homepage = "https://github.com/lauthals/eremit"
tags = ["blog", "minimal", "dark", "responsive"]
features = [
  "single column",
  "featured image",
  "social icons",
  "google analytics",
  "disqus"
]
min_version = 0.43

[author]
  name = "lauthals"
  homepage = "https://www.weissborn.me"
